name: vhv_basic
description: A package Colombo basic.
version: 0.0.1
homepage: https://colombo.vn
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.2.0'

dependency_overrides:
  fwfh_text_style: ^2.7.3+1
  video_player_android: 2.3.1
dependencies:
  platform: ^3.1.0
  flutter:
    sdk: flutter
  video_player: ^2.3.0
  flutter_cache_manager: ^3.1.2
  path_provider: ^2.0.8
  intl: ^0.17.0
  dio: ^4.0.4
  dio_http_cache: ^0.3.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  sweet_cookie_jar: ^1.0.4
  bot_toast: ^4.0.1
  sembast: ^3.1.1+1
  transformer_page_view:
    git:
      url: git://github.com/zeswen/transformer_page_view.git
      ref: master
  animations: ^2.0.2
  image_cropper: ^1.5.0
  url_launcher: ^6.0.17
  youtube_player_flutter: ^8.0.0
  timeago: ^3.2.2
  file_picker: ^4.5.1
  image_picker: ^0.8.4+4
  font_awesome_flutter: ^10.1.0
  flutter_html:
    path: ../../3rdparty/flutter_html-2.2.0
  pdfx: ^2.0.1+2
  flutter_svg: ^1.0.3
  permission_handler: ^9.2.0
  cached_network_image: ^3.2.0
  multi_image_picker: ^4.8.01
  flutter_absolute_path:
    path: ../../3rdparty/flutter_absolute_path_nullsafety
  downloads_path_provider_28: ^0.1.2
  html_unescape: ^2.0.0
  get: ^4.6.1
  get_storage: ^2.0.3
  hive: ^2.1.0
  hive_flutter: ^1.1.0
#  package_info: ^2.0.2
  package_info_plus: ^1.4.0
  connectivity_plus: ^2.2.1
  flutter_inappwebview: ^5.3.2
  better_player: ^0.0.81
#  dart_vlc: ^0.1.9
  card_swiper: ^2.0.3
  latlong2: ^0.8.1
  photo_view: ^0.13.0
  flutter_exif_rotation: ^0.5.0
  flutter_localizations:
    sdk: flutter
  syncfusion_flutter_datepicker: ^19.4.56
  geolocator: ^8.2.0
  flutter_tagging:
    path: ../../3rdparty/flutter_tagging
  flutter_widget_from_html:
    path: ../../3rdparty/flutter_widget_from_html-0.7.0
  wechat_assets_picker:
    path: ../../3rdparty/flutter_wechat_assets_picker
  flutter_map:
    path: ../../3rdparty/flutter_map_nullsafety
  bottom_picker:
    path: ../../3rdparty/bottom_picker
  html_editor:
    path: ../../3rdparty/flutter_html_editor
  syncfusion_localizations: ^19.4.38+1

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/maps/
    - assets/
